# Generated by Django 6.0.3 on 2026-05-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='motivo_rectificacao',
            field=models.TextField(blank=True, verbose_name='Motivo da rectificação'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='movimentacao_origem',
            field=models.ForeignKey(blank=True, help_text='Preenchido automaticamente nos estornos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='estoque.movimentacao', verbose_name='Movimentação de origem'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='rectificada',
            field=models.BooleanField(default=False, verbose_name='Rectificada'),
        ),
    ]
