# Generated by Django 6.0.3 on 2026-06-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_movimentacao_motivo_rectificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventario',
            name='acerto_aplicado',
            field=models.BooleanField(default=False, help_text='Indica se o acerto de estoque já foi aplicado para este inventário.', verbose_name='Acerto aplicado'),
        ),
    ]
