# Generated by Django 6.0.3 on 2026-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_iteminventario_acerto_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='acerto_aplicado',
            field=models.BooleanField(default=False, help_text='Indica se o acerto de estoque já foi aplicado.', verbose_name='Acerto aplicado'),
        ),
    ]
