# Generated by Django 6.0.3 on 2026-06-10 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_inventario_acerto_aplicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_inicial', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade inicial')),
                ('quantidade_restante', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade restante')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitário')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de entrada')),
                ('esgotado', models.BooleanField(default=False, verbose_name='Esgotado')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('movimentacao_origem', models.ForeignKey(help_text='Entrada que criou este lote', on_delete=django.db.models.deletion.PROTECT, related_name='lotes_criados', to='estoque.movimentacao', verbose_name='Movimentação de origem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'ordering': ['produto', 'data_entrada'],
            },
        ),
    ]
