# Generated by Django 6.0.3 on 2026-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_loteestoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventario',
            name='acerto_aplicado',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='acerto_aplicado',
            field=models.BooleanField(default=False, help_text='Indica se o acerto de estoque já foi aplicado para este inventário.', verbose_name='Acerto aplicado'),
        ),
    ]
