# Generated by Django 6.0.3 on 2026-06-10 11:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_iteminventario_acerto_aplicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='custo_medio',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Custo médio'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
